### PR TITLE
Upgrade prompt_toolkit to 0.52.

### PR DESCRIPTION
**Pull request by amjith**
@eliangcs This is an upgrade of the prompt toolkit library to 0.52. I'd highly encourage you to test this PR thoroughly before merging. 

Changelog for prompt_toolkit (https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG). 

Here are the pending PRs for pgcli and mycli for this exact same change. 

pgcli - https://github.com/dbcli/pgcli/pull/362
mycli - https://github.com/dbcli/mycli/pull/159

### CODE REVIEW

**Comment by amjith** [comment]
I had to disable the mouse support since it made it impossible to copy the output.

**Comment by amjith** [comment]
Don't merge this one. There is a bug in prompt_toolkit where the prompt has extra characters and the enter key seems broken in windows.

**Comment by eliangcs** [comment]
Sorry for late reply. Although you have discard the branch, I tested it using `behave` on Mac and it didn't pass.

**Comment by amjith** [comment]
Yes there was a bug in prompt_toolkit that was adding a few extra characters in the prompt.

**Pull request closed without merging**
