### PR TITLE
Add support of "WITH" queries

### PR DESCRIPTION
**Pull request by fl00r**
fixing

https://github.com/dbcli/vcli/issues/49

### CODE REVIEW

**Comment by fl00r** [comment]
> All checks have failed

ok :)

**Comment by eliangcs** [comment]
@fl00r Thank you for fixing the bug. It's nice to see people still use this tool, but I don't use it personally anymore and have little time to maintain this project. Are you interested in maintaining this project? I'd love to transfer the ownership of the package on PyPI.

**Comment by fl00r** [comment]
@eliangcs, hey!

I am not a Python guy :). So I am not a good choice for this role :/

**Comment by eliangcs** [comment]
@fl00r Too bad :(
@vladserkoff Can you confirm if this fixes issue #49 ?

**Comment by vladserkoff** [comment]
@eliangcs, nice, this fixes it!

**Pull request merged**
